

package database_project2;


import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanjim
 */

public class AddNewRoom extends javax.swing.JFrame {

    /**
     * Creates new form AddNewRoom
     */
    String AdminID;
    
    
    public AddNewRoom() {
        initComponents();
    }
    public AddNewRoom(String AdminId) {
        
        this.AdminID = AdminId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        floor = new javax.swing.JTextField();
        roomNo = new javax.swing.JTextField();
        buildingNo = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        totalBed = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 570));
        setMinimumSize(new java.awt.Dimension(1050, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Room");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backButton)
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Floor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total Bed:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Select Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Room No:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Building No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ac");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Non-Ac");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        floor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                floorKeyTyped(evt);
            }
        });
        getContentPane().add(floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 360, 40));

        roomNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomNoKeyTyped(evt);
            }
        });
        getContentPane().add(roomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 360, 40));

        buildingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingNoActionPerformed(evt);
            }
        });
        buildingNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buildingNoKeyTyped(evt);
            }
        });
        getContentPane().add(buildingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 360, 40));

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 140, 30));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 120, 30));

        totalBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "One", "Two", "Three", "Four", "Five" }));
        getContentPane().add(totalBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 360, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        buttonGroup1.clearSelection();
        buildingNo.setText("");
        floor.setText("");
        roomNo.setText("");
        totalBed.setSelectedIndex(0);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void buildingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildingNoActionPerformed

    private void buildingNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buildingNoKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_buildingNoKeyTyped

    private void floorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_floorKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_floorKeyTyped

    private void roomNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomNoKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_roomNoKeyTyped

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(buildingNo.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Building No is Empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(floor.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Floor No is Empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(roomNo.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Room No is Empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false )
        {
            JOptionPane.showMessageDialog(this,"Type is not Selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(totalBed.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Total Bed is Empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String query = buildingNo.getText()+(floor.getText().length()>1 ? floor.getText() : "0"+floor.getText()) +(roomNo.getText().length()>1 ? roomNo.getText() : "0"+roomNo.getText());
            ArrayList <RoomInfo> data = new ArrayList();
            
            data  =new ConnectMSSQL().getRoomInfo("where RoomId='"+query+"'");
            
            if(data.size()>0)
            {
                JOptionPane.showMessageDialog(this,"Same room already exist", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                RoomInfo room  =new RoomInfo();
                room.setBuildingNo(buildingNo.getText());
                room.setRoomId(query);
                room.setFloor(floor.getText());
                room.setType(jRadioButton1.isSelected() ? "Ac" : "Non-Ac");
                room.setTotalBed(totalBed.getSelectedIndex());
                room.setEmptyBed(totalBed.getSelectedIndex());
                new ConnectMSSQL().addRoom(room);
                JOptionPane.showMessageDialog(this,"Room added Successfully");
                resetButtonActionPerformed(evt);
                
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new Room(this.AdminID).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewRoom().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField buildingNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField floor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField roomNo;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> totalBed;
    // End of variables declaration//GEN-END:variables
}
